[versions]
agp = "8.12.0"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activityCompose = "1.10.1"
androidx-lifecycle = "2.9.1"
coil3 = "2.5.1"
compose-multiplatform = "1.8.2"
kotlin = "2.2.0"
room_version = "2.7.2"
ksp = "2.1.20-1.0.31"
sqlite = "2.5.2"
ktor-bom = "3.2.3"
koin-bom = "4.1.0"
koin-annotations-bom = "2.1.0"
kotlinx-datetime = "0.7.1"
navigation = "2.9.0-beta04"
composeIcons = "1.1.1"
materialKolor = "3.0.1"
config = "0.17.1"
store = "5.1.0-alpha06"

[libraries]
landscapist-coil3 = { module = "com.github.skydoves:landscapist-coil3", version.ref = "coil3" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
ktor = { module = "io.ktor:ktor-bom", version.ref = "ktor-bom" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-annotations-bom = { module = "io.insert-koin:koin-annotations-bom", version.ref = "koin-annotations-bom" }
koin-annotations = { module = "io.insert-koin:koin-annotations" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations-bom" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room_version" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room_version" }
sqlite-bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }

navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
icons = { group = "br.com.devsrsouza.compose.icons", name = "font-awesome", version.ref = "composeIcons" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
store = { module = "org.mobilenativefoundation.store:store5", version.ref = "store" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room_version" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "config" }